/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedImproveRouteImport } from './routes/_authenticated/improve'
import { Route as AuthenticatedLocationsRouteImport } from './routes/_authenticated/locations'
import { Route as AuthenticatedRatingsRouteImport } from './routes/_authenticated/ratings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedResponseCenterRouteImport } from './routes/_authenticated/response-center'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated/reviews'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImproveRoute = AuthenticatedImproveRouteImport.update({
  id: '/improve',
  path: '/improve',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLocationsRoute = AuthenticatedLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRatingsRoute = AuthenticatedRatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResponseCenterRoute =
  AuthenticatedResponseCenterRouteImport.update({
    id: '/response-center',
    path: '/response-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/improve': typeof AuthenticatedImproveRoute
  '/locations': typeof AuthenticatedLocationsRoute
  '/ratings': typeof AuthenticatedRatingsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/response-center': typeof AuthenticatedResponseCenterRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/improve': typeof AuthenticatedImproveRoute
  '/locations': typeof AuthenticatedLocationsRoute
  '/ratings': typeof AuthenticatedRatingsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/response-center': typeof AuthenticatedResponseCenterRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/improve': typeof AuthenticatedImproveRoute
  '/_authenticated/locations': typeof AuthenticatedLocationsRoute
  '/_authenticated/ratings': typeof AuthenticatedRatingsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/response-center': typeof AuthenticatedResponseCenterRoute
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/alerts'
    | '/analytics'
    | '/improve'
    | '/locations'
    | '/ratings'
    | '/reports'
    | '/response-center'
    | '/reviews'
    | '/settings'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/alerts'
    | '/analytics'
    | '/improve'
    | '/locations'
    | '/ratings'
    | '/reports'
    | '/response-center'
    | '/reviews'
    | '/settings'
    | '/team'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/alerts'
    | '/_authenticated/analytics'
    | '/_authenticated/improve'
    | '/_authenticated/locations'
    | '/_authenticated/ratings'
    | '/_authenticated/reports'
    | '/_authenticated/response-center'
    | '/_authenticated/reviews'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/improve': {
      id: '/_authenticated/improve'
      path: '/improve'
      fullPath: '/improve'
      preLoaderRoute: typeof AuthenticatedImproveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/locations': {
      id: '/_authenticated/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AuthenticatedLocationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ratings': {
      id: '/_authenticated/ratings'
      path: '/ratings'
      fullPath: '/ratings'
      preLoaderRoute: typeof AuthenticatedRatingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/response-center': {
      id: '/_authenticated/response-center'
      path: '/response-center'
      fullPath: '/response-center'
      preLoaderRoute: typeof AuthenticatedResponseCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedImproveRoute: typeof AuthenticatedImproveRoute
  AuthenticatedLocationsRoute: typeof AuthenticatedLocationsRoute
  AuthenticatedRatingsRoute: typeof AuthenticatedRatingsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedResponseCenterRoute: typeof AuthenticatedResponseCenterRoute
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedImproveRoute: AuthenticatedImproveRoute,
  AuthenticatedLocationsRoute: AuthenticatedLocationsRoute,
  AuthenticatedRatingsRoute: AuthenticatedRatingsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedResponseCenterRoute: AuthenticatedResponseCenterRoute,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
